# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20161212_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(default=1, upload_to='note_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(default=1, upload_to='note_images'),
            preserve_default=False,
        ),
    ]
