# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20161212_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='document',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
