# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='name',
        ),
    ]
